services:
  service:
    container_name: search_engine
    build:
      context: ../
      dockerfile: build/docker/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "9000:9000"
    volumes:
      - ../:/app
    env_file: ".env"
    environment:
      - POSTGRES_ADDRESS=postgres
    # command: >
    #   sh -c 'make run-service'


  postgres:
    container_name: search_engine_db
    image: postgres:13
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}"]
      interval: 3s
      timeout: 30s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/repository/data
    env_file: ".env"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

  migrate:
    container_name: search_engine_db_migrate
    image: migrate/migrate:4
    command: -path=../migrations/ -database "postgres://${DB_USERNAME}:${DB_PASSWORD}@postgres:5432/${DB_NAME}?sslmode=${DB_SSLMODE}" up
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ../migrations:/migrations:ro
    env_file: ".env"

volumes:
  postgres_data: