data_links:
  - url: "https://www.gazeta.ru/politics/news/2024/10/23/24218251.shtml"
    title_selector: "a.b_ear.m_simple"
    title_text: "div.b_ear-title"
    article_selector: "div.b_article-text p"
    article_link: "a"

  # - url: "https://lenta.ru"
  #   selector: "a.card-mini._topnews"
  #   text: "h3.card-mini__title"
  # - url: "http://ngs.ru"
  #   selector: "a.link_SrG8j"
  #   text: "div.title_SrG8j"
