data_links:
  - url: "https://www.gazeta.ru/"
    title_link_tag: "a.b_ear"
    title_text_tag: "div.b_ear-title"
    article_link_tag: "a"
    article_text_tag: "div.b_article-text p"
  - url: "https://lenta.ru"
    title_link_tag: "a.card-mini._topnews"
    title_text_tag: "h3.card-mini__title"
    article_link_tag: "a"
    article_text_tag: "topic-body__content-text"
  - url: "http://ngs.ru"
    title_link_tag: "a.link_SrG8j"
    title_text_tag: "div.title_SrG8j"
    article_link_tag: "a"
    article_text_tag: "uiArticleBlockText_g83x5"
