data_links:
  - url: "https://www.gazeta.ru/"
    title_text_tag: "div.b_ear-title"
    title_link_tag: "a.b_ear"
    article_text_tag: "div.b_article-text p"
    article_link_tag: "a"

  # - url: "https://lenta.ru"
  #   selector: "a.card-mini._topnews"
  #   text: "h3.card-mini__title"
  # - url: "http://ngs.ru"
  #   selector: "a.link_SrG8j"
  #   text: "div.title_SrG8j"
